@Restaurants.API_HostAddress = https://localhost:7243

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants?PageNumber=2&PageSize=5&SortBy=Nam

###
